spring:
  data:
    mongodb:
      uri : mongodb+srv://dbmaster:dbmaster@cluster0.pdlt3fa.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database : Task

  # security:
  #   oauth2:
  #     client:
  #       registration:
  #         auth0:
  #           client-id: XkeNGZfZssp0gpDmol7ixM9W9XrfRVNA
  #           client-secret: S76JNzrSHrwOE8JTOZYpMo0H5JYk_uMiS7K9YX1B5qVaAicUcJcPttH-CaMJDNrq
  #           authorization-grant-type: authorization_code
  #           redirect-uri: "{baseUrl}/login/oauth2/code/auth0"
  #           scope: openid, profile, email
  #       provider:
  #         auth0:
  #           issuer-uri: https://autharmour.au.auth0.com/